version: '3'
services:
  postgresql:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis_base
    ports:
      - "6379:6379"
